FROM python:3.11-slim

WORKDIR /app

# system deps for pyodbc if needed (comment if not using)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    unixodbc-dev \
    gcc \
    g++ \
 && rm -rf /var/lib/apt/lists/*

COPY ml/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ml/ /app/

EXPOSE 8000
CMD ["uvicorn", "inference_service:app", "--host", "0.0.0.0", "--port", "8000"]

