FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY api-gateway-csharp/ ./api-gateway-csharp/
WORKDIR /src/api-gateway-csharp
RUN dotnet restore
RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .
ENV PYTHON_API_URL=http://python-ml:8000
EXPOSE 8080
ENTRYPOINT ["dotnet", "api-gateway-csharp.dll"]

